/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gc.gui;

import gc.dao.AdminDAO;
import gc.dao.ClientDAO;
import gc.dao.PrestataireDAO;
import gc.entities.Admin;
import gc.entities.Client;
import gc.entities.Globale;
import gc.entities.Prestataire;


/**
 *
 * @author STETCHI
 */
public class Athentification extends javax.swing.JFrame {

    /**
     * Creates new form Athentification
     */
    public Athentification() {
        initComponents();
        faux.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jmail = new javax.swing.JTextField();
        jpwd = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        faux = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mail :");

        jLabel2.setText("Password :");

        jButton1.setText("se connecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        faux.setText("Mot de passe ou mail incorrect ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jpwd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jmail, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(faux)))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(faux)
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AdminDAO admindao = new AdminDAO();
        PrestataireDAO prestatairedao = new PrestataireDAO();
        ClientDAO clientdao = new ClientDAO();
        
        Admin admin = new Admin("","");
       
        Prestataire prestataire = new Prestataire(0, "", "", 0, "", "", "", 0, "", "");
       
        Client client = new Client(0, "", "", 0, "", "", "", 0);
       
        Globale global = new Globale();
        
          admin = admindao.findAdminByMail(jmail.getText(),jpwd.getText());
         prestataire= prestatairedao.findPrestataireByMailPwd(jmail.getText(),jpwd.getText());
         client = clientdao.findClientByMailPwd(jmail.getText(),jpwd.getText());
        
         if(admin.getId_admin() != 0)
        {
      
        global.setId(admin.getId_admin());
        global.setMail(admin.getMail());
        
        ConsulterReclamation cr = new ConsulterReclamation();
        this.setVisible(false);
        cr.setVisible(true);
        
        }
        else if(prestataire.getId_prestataire() !=0 )
        {
            global.setId(prestataire.getId_prestataire());
            global.setNom(prestataire.getNom());
            global.setPrenom(prestataire.getPrenom());
            global.setMail(prestataire.getMail());
            
            AjouterOffre ao = new AjouterOffre();
            this.setVisible(false);
            ao.setVisible(true);
        }
        
        else if(client.getId_client() != 0){
            global.setId(client.getId_client());
            global.setNom(client.getNom());
            global.setPrenom(client.getPrenom());
            global.setMail(client.getMail());
            
            ConsulterCommentaire cc = new ConsulterCommentaire();
            this.setVisible(false);
            cc.setVisible(true);
        }
        else {
            faux.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Athentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Athentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Athentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Athentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Athentification().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel faux;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jmail;
    private javax.swing.JTextField jpwd;
    // End of variables declaration//GEN-END:variables
}
